name: AWS OIDC GITHUB
on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION : "us-east-1"   
permissions:
      id-token: write
      contents: read

jobs:
  OIDC:
    name: 'OIDC'
    runs-on: ubuntu-latest
    environment: oidc
    defaults:
      run:
        shell: bash
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::190836357141:role/GitHubActionsOIDCRole_1
          # role-session-name: samplerolesession
          aws-region: us-east-1
      - name: Print Assumed Role
        run: aws sts get-caller-identity
      - name: Print s3 buckets
        run: aws s3 ls







# # This is a basic workflow to help you get started with Actions

# name: OpenId
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   OpenId-Connector:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Configure AWS credentials using OIDC
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
#         aws-region: ${{ secrets.AWS_REGION }}

#     - name: Debug AWS credentials
#       run: |
#          aws sts get-caller-identity


#       # Runs a single command to list all the buckets
#     - name: List all S3 buckets
#       run: aws s3 ls --region us-east-1
